# Generated by Django 2.0.7 on 2018-07-11 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20180710_0633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cryptokey',
            unique_together={('private_key', 'public_key', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together={('content', 'key', 'user')},
        ),
    ]
