# Generated by Django 2.0.7 on 2018-07-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Plaintext title', max_length=250, null=True)),
                ('content', models.TextField(default=None, help_text='Encrypted content', null=True)),
                ('owner', models.ForeignKey(help_text='Owner of this object', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(help_text='RSA private key', max_length=2048)),
                ('public_key', models.CharField(help_text='RSA public key', max_length=2048)),
                ('is_revoked', models.BooleanField(default=False, help_text='Set to revoke access')),
                ('user', models.ForeignKey(help_text='Authorized user to access content', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Encrypted key', max_length=32)),
                ('is_revoked', models.BooleanField(default=False, help_text='Set to revoke access')),
                ('content', models.ForeignKey(help_text='Encrypted content', on_delete=django.db.models.deletion.CASCADE, to='notes.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
