# Generated by Django 2.0.7 on 2018-07-10 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptokey',
            name='user',
            field=models.OneToOneField(help_text='Authorized user to access content', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='key',
            name='content',
            field=models.ForeignKey(help_text='Encrypted content', on_delete=django.db.models.deletion.CASCADE, related_name='aeskey', to='notes.Content'),
        ),
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(help_text='Encrypted key', max_length=272),
        ),
    ]
